source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SwiftElegantDropdownMenu_Example', :exclusive => true do
  pod "SwiftElegantDropdownMenu"
end

target 'SwiftElegantDropdownMenu_Tests', :exclusive => true do
  pod "SwiftElegantDropdownMenu"

  
end
